export * from './readonly-input/readonly-input.component';
export * from './personal-details/personal-details.component';
export * from './document-details/document-details.component';
export * from './delivery-details/delivery-details.component';
export * from './application-details/application-details.component';
export * from './address-details/address-details.component';
export * from './card-details/card-details.component';
export * from './integration-status/integration-status.component';
export * from './emergency-contact-details/emergency-contact-details.component';
export * from './dependent-details/dependent-details.component'
export * from './preferred-collection-details/preferred-collection-details.component';
