
 export const data:any =   [{"id":1,
        "name":"Agent Name",
      "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":2,
      "name":"Agent Name2",
    "userType":"User Type2",
    "serviceCentre":"Service Centre2",
    "printerName":"Printer Name2",
  "agentemail":"email2@k.com",
"agnetphone":756768992},
    {"id":3,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":4,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":5,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":6,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":7,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":9,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":10,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":11,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":12,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":13,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":14,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":15,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":16,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":17,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":18,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":19,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":20,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":21,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":22,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899},
    {"id":23,
      "name":"Agent Name",
    "userType":"User Type",
    "serviceCentre":"Service Centre",
    "printerName":"Printer Name",
  "agentemail":"email@k.com",
"agnetphone":75676899}
    ]
        