export const ApiUrls = {
  Login: '/api/Account/login',
  LoginSC:'/api/Account/loginServiceCenter',
  LoginBr:'/api/Account/loginBulkRegister',
  ChangePassword: '/api/Account/changePassword',
  ProfilePost: '/account/profile-post',
  ProfileInitiate: '/account/profile-initiate',
  DashboardEvents: '/api/Tournament/tournamentDashboardList',
  B2BDashboardStatistics: '/api/Statistics/get-register-B2B-statistics',
  DashboardStatistics: '/api/Statistics/get-register-statistics',
  Events: '/dashboard/events',
  EventsTournament:'/api/Tournament/getList',
  Organizations: '/api/Organization/getList',
  Organization: '/api/Organization/getById',
  ServiceCenters: '/bulk-upload/servicecentres',
  UploadExcel: '/api/BulkRegistration/uploadBulkRegistraionFile',
  ImportHeaderInfo: '/bulk-upload/importheaderdetails',
  BulkImportData: '/bulk-upload/bulkimport',
  SubmissionStatus: '/bulk-upload/submittedstatus',
  ToProcess: '/api/BulkRegistrationDraft/Bulk-Registration-Submit',
  BulkGroups: '/api/BulkRegistrationDraft/Get-Bulk-Group-Name-List',
  // BulkGroupData: '/bulk-group/bulkgroupdata',
  GetBulkGroupList:"/api/BulkRegistrationDraft/get-List",
  BulkGroupData: '/api/BulkRegistrationDraft/Get-List-By-Bulk-Group-Name',
  FilteredBulkGroupData: '/bulk-group/filterwithbulkgroup',
  ApplicationStatistics: '/api/BulkRegistrationDraft/Get-Appliction-Status-Statistics',
  AllApplicationData: '/bulk-group/allapplicationdata',
  FilteredColumnData: '/bulk-group/filterwithcolumn',
  ColumntoFilter: '/bulk-group/columntofilter',
  UploadManualData: '/manual-upload/uploadmanualdata',
  FanCategories: '/manual-upload/fan-categories',
  Countries: '/manual-upload/countries',
  Professions: '/manual-upload/professions',
  Phonecodes: '/manual-upload/phonecodes',
  Titles: '/manual-upload/titles',
  Medicals: '/manual-upload/medicals',
  UserCategories: '/manual-upload/user-categories',
  ManualImportHeaderInfo: '/manual-upload/importheaderdetails',
  ManualBulkImportData: '/manual-upload/bulkimport',
  ManualSubmissionStatus: '/manual-upload/submittedstatus',
  ManualToProcess: '/manual-upload/postimporteddata',
  ManualRegister: '/manual-upload/manualregister',
  AllApplicationListData: '/api/CustomerCardApplication/get-List',
  ListColumntoFilter: '/all-applications/columntofilter',
  ListFilteredColumnData: '/all-applications/filterwithcolumn',
  ApplicantData: '/api/CustomerCardApplication/get-by-fanid',
  TerminalList: '/api/Terminal/getList',
  PrinterList:'/api/PrinterMap/getListByName',
  CardReplacementColumntoFilter:
    '/card-replacement/cardReplacementcolumntofilter',
  CardReplacementListData: '/api/CustomerCardApplication/get-List-by-Service-Center',
  CardReplacementApplicantData:
    '/card-replacement/CardReplacementApplicantData',
  CardPickupFilterColumns: '/card-pickup/cardPickupFilter',
  CardPickupListData: '/card-pickup/cardPickupData',
  CardPickupIndvidualData: '/card-pickup/CardReplacementApplicantData',
  CardPrintStatus: '/api/CustomerCardApplication/get-Dependent-List',
  otpSMSSend: '/api/Otp/sendSmsOtp',
  otpSMSVerify: '/api/Otp/validateSmsOtp',
  cardPickupPrintCardData:'/api/CustomerCard/get-card-details-by-fan-ids',
  CustomerCardPrinting:'/api/CustomerCardPrinting/PrintCard',
  GetImage:'/api/CustomerCardApplication/getImage',
  ForgotPassword:'/api/Account/forgotPassword',
  sendforgotEmail:'/api/Account/sendForgotPasswordEmail',
  ProfileDataBR: '/api/profile/getProfileForBr',
  ProfileDataSC: '/api/profile/getProfileForSc',
  ProfileUpdate: '/api/profile/updateProfile',
  ValidateBulkGroupName:'/api/BulkRegistration/ValidateBulkGroupsName',
  DeleteBulkUploadDraft:'/api/BulkRegistrationDraft/Bulk-Delete-Draft-Data',
  UpdateOcr:'/api/BulkRegistrationDraft/UpdateFMAndOcr',
  ExportExcel:'/api/BulkRegistration/ExportFailedApplications',
  ExportTemplate:'/api/BulkRegistration/DownloadExcelTemplate',
  UserPermissions:'/api/Permission/getUserModulePermissions',
  ValidateUserInvite:'/api/SystemUserInvitation/validateInvitationEmailLink',
  DailingCode:"/api/SystemUserInvitation/getDialingCodeDropDownList",
  SignUp:"/api/SystemUserInvitation/signupUser",
  SendOtp:"/api/SystemUserInvitation/sendForgotPasswordEmailOtp",
  ForgotPasswordOtp:"/api/SystemUserInvitation/forgotPassword",
  ResetPasswordOtp:"/api/SystemUserInvitation/resetPassword",
  ValidateQid:'/api/BulkRegistrationDraft/validateQidPersonalDetails',
  ApplicationType:'/api/ApplicationType/getList',
  GetKnowledgeBaseDocuments:'/api/TrainingManual/getTrainingManual',
  DownloadDocument:'/api/TrainingManual/GetFile',
  GetAccessToken:"/api/Token/getAccessToken",
  ResendLoginOTP:"/api/Token/sendLoginOtp",
  OnBoardOrganization:"/api/OrgSignup/submit",
  EditOrganization:"/api/Organization/UpdateDetails",
  ValidateOrganization:"/api/OrgSignup/validateLink",
  SubmitOrganization:"/api/OrgSignup/signupSubmit ",
  PackageUploadList: "/api/PackageUpload/Get-Package-Upload-Bulk-Group-List",
  ResendOrganizationInvite:"/api/OrgSignup/resendEmail",
  ResendUserInvite:"/api/OrgSignup/resendInvitationEmail",
  GetOrgListById:'/api/OrgSignup/viewDetails',
  DownloadOrgTemplate:'/api/Organization/DownloadOrganizationTemplate',
  InviteOrgUser:'/api/OrgSignup/orgAddUser',
  PackageTemplate:'/api/PackageUpload/DownloadPackageZipTemplate',
  UpdateBulkGroupAccommodationDetails:"/api/BulkRegistration/Update-OrgGroup-Accommodation-Address",
  VerifyApplicationUpdateStatus: "/api/CustomerCardApplicationStatus/PendingApplicationVerification_UpdateStatus",
  GetCategoryList:'/api/RegUserCategory/getList',
  GetOrgById:'/api/Organization/getById',
  GetOrganzationCategoryList:'/api/OrganizationCategory/getList',
  EditOrganizationUserAppCount:'/api/SystemUser/UpdateUserMaxApplicantAndVoucherCount',
  GetActiveConferenceEventList:'/api/ConferenceEvent/ReadAllActiveConferenceEventList',
  CreateOrder: '/api/PaymentTransactions/CreateOrder',
  BulkCreateOrder:'/api/PaymentTransactions/BulkCreateOrder',
  GetPaymentAmount: '/api/PaymentTransactions/GetPaymentAmount',
  GetBulkPaymentAmount:'/api/PaymentTransactions/GetBulkPaymentAmount',
  GetConferencesByCode: '/api/ConferenceEvent/V1/GetConferencesByCode',
  GetConferenceFieldsAndRules: '/api/ConferenceEvent/GetConferenceFieldsAndRulesByServiceId'
};
